name: Build and push docker image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  change_dockerfile:
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.changed-files-specific.outputs.any_changed }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: changed-files-specific
        uses: tj-actions/changed-files@v44
        with:
          files: |
            Dockerfile
            .github/workflows/*.yml

  build_and_push:
    if: (needs.change_dockerfile.outputs.any_changed == 'true')
    needs: change_dockerfile
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=branch
      - if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
